table_name: sales_ts
columns:
  - name: TSDate
    type: TIMESTAMP
  - name: serieNames
    type: STRING
  - name: sales
    type: INTEGER
  - name: year
    type: INTEGER
  - name: month
    type: INTEGER
  - name: day
    type: INTEGER
  - name: weekday_num
    type: INTEGER
  - name: week_number
    type: INTEGER
  - name: is_weekend
    type: INTEGER
  - name: dutch_event
    type: INTEGER
  - name: is_liberation_day
    type: INTEGER
  - name: is_mothers_day
    type: INTEGER
  - name: is_fathers_day
    type: INTEGER
  - name: is_veterans_day
    type: INTEGER
  - name: is_valentines_day
    type: INTEGER
  - name: is_halloween
    type: INTEGER
  - name: is_thanksgiving
    type: INTEGER
  - name: is_black_friday
    type: INTEGER
  - name: is_cyber_monday
    type: INTEGER
  - name: is_easter
    type: INTEGER
  - name: is_easter_monday
    type: INTEGER
  - name: is_sinterklaas
    type: INTEGER
  - name: is_christmas
    type: INTEGER
  - name: season
    type: INTEGER
  - name: lag_1
    type: FLOAT
  - name: lag_2
    type: FLOAT
  - name: lag_3
    type: FLOAT
  - name: lag_4
    type: FLOAT
  - name: lag_5
    type: FLOAT
  - name: lag_6
    type: FLOAT
  - name: lag_7
    type: FLOAT
  - name: rolling_min
    type: FLOAT
  - name: rolling_max
    type: FLOAT
  - name: rolling_std
    type: FLOAT
